# syntax=docker/dockerfile:1
FROM node:14-slim 
WORKDIR /usr/src/app
COPY ./package.json ./
COPY ./yarn.lock ./ 
ARG NODE_ENV
RUN yarn install --only=production

COPY . .
ENV PORT 8080
EXPOSE ${PORT}
CMD [ "yarn" , "run" , "prod" ]
